RCS=	\
	Makefile \
	btree.h \
	externs.h \
	io.h \
	regexp.h \
	store.h \
	syssym.h \
	ubermud.h

all:	$(RCS)
	@echo done

lint:	$(RCS)

clean:
clobber:
	
ci:
	ci -t/dev/null -m" " -u $(RCS) < /dev/null
